[2024-04-18T02:47:37.323+0000] {task_context_logger.py:104} ERROR - Executor reports task instance <TaskInstance: example_sensors.success_sensor_python manual__2024-04-18T02:47:33.787232+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
